name: OTP-loging react js

# Push - action will trigger if someone pushes to the main branch
# Pull request - action will trigger if someone opens a pull request from the main branch.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # build
  build:
    runs-on: windows-latest

    steps:
      # actions/checkout basically performs a local git clone of the repository

      - name: Checkout repository
        uses:
          actions/checkout@v3

          # actions/setup-node@v1. This action takes care of installing Node.js inside the container running our job
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  # Deploy Job
  deploy:
    # Add a dependency to the build job
    needs: build
    # Specify runner + deployment step
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.OTP_CI_CD_SECRET }}
          publish_dir: ./dist
